; c64.ini -- configuration for c64.exe
; This file must be encoded as UTF-8.

[c64]
; home: Sets the HOME environment variable for c64 sessions. This path may be
; relative to c64.exe and may contain %%ENVIRONMENT_VARIABLES%%.
;
; title: Sets the initial console title. This value may contain environment
; variables.
;
;home = ..\home
;home = %HOMEDRIVE%%HOMEPATH%
;title = %USERNAME%@%COMPUTERNAME% [%C64_HOME% %C64_VERSION%]
